services:
  - type: web
    name: ingichka-smart-store-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot/bot_app.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PYTHONUNBUFFERED
        value: "1"

