"""
services/handoff_service.py
TASK 5: Human handoff. Strictly follows RULES.md.

1. Handoff triggers:
   - Customer asks for a human (uz/ru/en)
   - Anger or complaint words
   - Grounding validator failed twice
   - 2 consecutive "I don't know" answers
2. On trigger:
   - Reply to customer: "Operatorga ulayman, tez orada javob beradi"
   - Send ADMIN_CHAT_ID: customer name/username, chat_id, 5-line chat summary
     (generated by LLM from real chat), reason for handoff.
3. While in handoff mode:
   - Bot stays silent to the customer.
   - Admin's reply to the forwarded message is delivered to the customer.
4. Admin command /bot_on <chat_id> returns the chat to the bot.
   - Auto-return after 6 hours of admin silence with a polite message.
5. Do not trigger handoff for normal questions.
"""

import os
import re
import json
import logging
import threading
from pathlib import Path
from datetime import datetime, timedelta
from typing import Dict, Any, Optional, List, Tuple, Callable

from utils.file_utils import atomic_write_json
from utils.logger import log_bot_error
from config import ADMIN_CHAT_ID, ADMIN_TELEGRAM_IDS

logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

HANDOFF_SESSIONS_FILE = DATA_DIR / "handoff_sessions.json"
MESSAGE_MAP_FILE = DATA_DIR / "handoff_message_map.json"

_HANDOFF_LOCK = threading.RLock()

# Standart javoblar va timeoutlar
CUSTOMER_HANDOFF_REPLY = "Operatorga ulayman, tez orada javob beradi"
AUTO_RETURN_MESSAGE = (
    "Kutganingiz uchun rahmat! Operatorlarimiz hozirda band bo'lgani sababli, "
    "savollaringizga men (aqlli yordamchi) davom ettiraman. Qanday yordam bera olaman?"
)
BOT_ON_CUSTOMER_MESSAGE = "Muloqot botga qaytarildi. Sizga yana qanday yordam bera olaman? 😊"

# 6 soat sukutdan so'ng avto-qaytish (sekundlarda)
DEFAULT_AUTO_RETURN_SECONDS = 6 * 3600  # 21600 seconds

# Trigger sabablari
REASON_HUMAN_REQUEST = "Mijoz jonli operator so'radi"
REASON_ANGER_COMPLAINT = "G'azab yoki shikoyat so'zlari aniqlandi"
REASON_GROUNDING_FAILED_TWICE = "Grounding validator failed twice"
REASON_CONSECUTIVE_UNKNOWN = "2 consecutive 'I don't know' answers"

# -------------------------------------------------------------
# Trigger Regex Patterns
# -------------------------------------------------------------
HUMAN_PATTERNS = [
    # Uzbek
    r"\boperator(?:ga|ni|dan|lar|lik)?\b",
    r"\bjonli\s+(?:odam|inson)\b",
    r"\bodam\s+bilan\b",
    r"\boperator\s+bilan\b",
    r"\binson\s+bilan\b",
    r"\bmutaxassis(?:lar)?\b",
    r"\bmenejer(?:lar)?\b",
    r"\badministrator\b",
    r"\boperatorga\s+ula\b",
    r"\boperator\s+kerak\b",
    r"\bodam\s+kerak\b",

    # Russian
    r"\bоператор(?:а|ом|у|ы)?\b",
    r"\bживой\s+человек\b",
    r"\bпозови\s+человека\b",
    r"\bсоедини\s+с\s+оператором\b",
    r"\bпереведи\s+на\s+оператора\b",
    r"\bпоговорить\s+с\s+человеком\b",
    r"\bменеджер(?:а|ом|у)?\b",
    r"\bадминистратор\b",

    # English
    r"\b(?:talk|speak)\s+to\s+(?:a\s+)?human\b",
    r"\bconnect\s+(?:me\s+)?to\s+(?:a\s+)?human\b",
    r"\bhuman\b",
    r"\breal\s+person\b",
    r"\blive\s+agent\b",
    r"\bsupport\s+agent\b",
    r"\bcustomer\s+representative\b",
    r"\boperator\b"
]

ANGER_COMPLAINT_PATTERNS = [
    # Uzbek
    r"\b(?:juda\s+)?yomon\b",
    r"\brasvo\b",
    r"\bdabdala\b",
    r"\baldadingiz\b",
    r"\baldayapsiz\b",
    r"\baldov\b",
    r"\bshikoyat(?:\s+qilaman)?\b",
    r"\basabim(?:ni)?\s+buzdingiz\b",
    r"\basab(?:im)?\s+buzildi\b",
    r"\bbema'ni(?:lik)?\b",
    r"\bfiribgar(?:lik)?\b",
    r"\btovlamachi(?:lik)?\b",
    r"\bnoroziman\b",
    r"\bjonga\s+tegdi\b",
    r"\blanat\b",
    r"\bahmoq\b",
    r"\bo'g'ri(?:lar)?\b",

    # Russian
    r"\bжалоба\b",
    r"\bпожалуюсь\b",
    r"\bужасно(?:е|й|я)?\b",
    r"\bотвратительно\b",
    r"\bобман(?:щики)?\b",
    r"\bвы\s+обманули\b",
    r"\bмошенник(?:и)?\b",
    r"\bверните\s+деньги\b",
    r"\bнадоели\b",
    r"\bбесит\b",
    r"\bкошмар\b",
    r"\bхамство\b",
    r"\bлохотрон\b",
    r"\bплохой\s+сервис\b",

    # English
    r"\bcomplaint\b",
    r"\bscam(?:mer|mers)?\b",
    r"\bfraud\b",
    r"\bawful\b",
    r"\bterrible\b",
    r"\bhorrible\b",
    r"\bangry\b",
    r"\bfurious\b",
    r"\bwaste\s+of\s+time\b",
    r"\bcheater(?:s)?\b",
    r"\bsue\s+you\b",
    r"\bridiculous\b",
    r"\bunacceptable\b"
]

UNKNOWN_PATTERNS = [
    r"\bbilmayman\b",
    r"\bma'lumot\s+(?:yo'q|mavjud\s+emas|topilmadi)\b",
    r"\bbu\s+haqida\s+ma'lumot\s+yo'q\b",
    r"\bbuni\s+egasidan\s+so'rab\b",
    r"\baniqlashtirib,?\s+operator\b",
    r"\baniqlashtirib\b",
    r"\bне\s+знаю\b",
    r"\bнет\s+информации\b",
    r"\bнет\s+данных\b",
    r"\bi\s+don't\s+know\b",
    r"\bi\s+do\s+not\s+know\b",
    r"\bno\s+information\b"
]


class HandoffService:
    """Inson operatoriga yo'naltirish (Human Handoff) boshqaruv xizmati"""

    AUTO_RETURN_TIMEOUT_SECONDS = DEFAULT_AUTO_RETURN_SECONDS

    # Ketma-ket noma'lum javoblar sanog'i: chat_id -> count
    _CONSECUTIVE_UNKNOWN_TRACKER: Dict[int, int] = {}

    # Admin xabarnoma yuboruvchi tashqi funksiya (Dependency Injection)
    _ADMIN_ALERT_SENDER: Optional[Callable[[str, int], Any]] = None

    # ---------------------------------------------------------
    # 1. Ma'lumotlarni saqlash va yuklash (Atomic JSON Storage)
    # ---------------------------------------------------------
    @classmethod
    def _load_sessions(cls) -> Dict[str, Any]:
        with _HANDOFF_LOCK:
            if not HANDOFF_SESSIONS_FILE.exists():
                return {}
            try:
                with open(HANDOFF_SESSIONS_FILE, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    if isinstance(data, dict):
                        return data
            except Exception:
                pass
            return {}

    @classmethod
    def _save_sessions(cls, sessions: Dict[str, Any]) -> None:
        with _HANDOFF_LOCK:
            atomic_write_json(str(HANDOFF_SESSIONS_FILE), sessions, indent=2)

    @classmethod
    def _load_message_map(cls) -> Dict[str, int]:
        with _HANDOFF_LOCK:
            if not MESSAGE_MAP_FILE.exists():
                return {}
            try:
                with open(MESSAGE_MAP_FILE, "r", encoding="utf-8") as f:
                    data = json.load(f)
                    if isinstance(data, dict):
                        return data
            except Exception:
                pass
            return {}

    @classmethod
    def _save_message_map(cls, message_map: Dict[str, int]) -> None:
        with _HANDOFF_LOCK:
            atomic_write_json(str(MESSAGE_MAP_FILE), message_map, indent=2)

    @classmethod
    def map_admin_message(cls, admin_message_id: int, customer_chat_id: int) -> None:
        """Admin xabari ID sini mijoz chat_id siga biriktirish"""
        m_map = cls._load_message_map()
        m_map[str(admin_message_id)] = customer_chat_id
        cls._save_message_map(m_map)

    @classmethod
    def get_customer_chat_id_from_admin_reply(
        cls,
        reply_to_message_id: int,
        reply_to_text: str = ""
    ) -> Optional[int]:
        """Admin javob bergan xabardan mijoz chat_id sini aniqlash"""
        m_map = cls._load_message_map()
        # 1. To'g'ridan-to'g'ri xarita bo'yicha qidirish
        if str(reply_to_message_id) in m_map:
            return int(m_map[str(reply_to_message_id)])

        # 2. Xabar matnidan regex orqali qidirish ("Chat ID: 123456" yoki "ID: 123456")
        if reply_to_text:
            m = re.search(r"(?:Chat\s*ID|ID)[:\s`]*([0-9]{5,15})", reply_to_text, re.IGNORECASE)
            if m:
                return int(m.group(1))

        # 3. Agar bitta faol handoff sessiyasi bo'lsa, o'shanga biriktirish
        active_sessions = [
            int(cid) for cid, s in cls._load_sessions().items()
            if s.get("status") == "active"
        ]
        if len(active_sessions) == 1:
            return active_sessions[0]

        return None

    @classmethod
    def set_admin_alert_sender(cls, sender_fn: Callable[[str, int], Any]) -> None:
        """Admin uchun asinxron xabarnoma yuboruvchini o'rnatish"""
        cls._ADMIN_ALERT_SENDER = sender_fn

    @classmethod
    def get_admin_chat_id(cls) -> Optional[int]:
        """Asosiy admin chat ID sini olish"""
        if ADMIN_CHAT_ID and ADMIN_CHAT_ID.lstrip("-").isdigit():
            return int(ADMIN_CHAT_ID)
        if ADMIN_TELEGRAM_IDS:
            return ADMIN_TELEGRAM_IDS[0]
        return None

    # ---------------------------------------------------------
    # 2. Triggerlarni aniqlash (Handoff Triggers)
    # ---------------------------------------------------------
    @classmethod
    def is_handoff_triggered(
        cls,
        text: str,
        chat_id: int,
        consecutive_unknown_count: int = 0,
        grounding_failed_twice: bool = False
    ) -> Tuple[bool, Optional[str]]:
        """
        Trigger tekshiruvi:
        1. Jonli operator so'rash (uz/ru/en)
        2. G'azab yoki shikoyat so'zlari
        3. Grounding validator 2 marta muvaffaqiyatsiz bo'lsa
        4. 2 marta ketma-ket noma'lum/bilmayman javobi
        5. Normal savollarda HECH QACHON trigger ishlamaydi.
        """
        if grounding_failed_twice:
            return True, REASON_GROUNDING_FAILED_TWICE

        if consecutive_unknown_count >= 2:
            return True, REASON_CONSECUTIVE_UNKNOWN

        if not text:
            return False, None

        t = text.lower().strip()

        # 1. Inson / Operator so'ralganda (uz / ru / en)
        for pat in HUMAN_PATTERNS:
            if re.search(pat, t, re.IGNORECASE):
                return True, REASON_HUMAN_REQUEST

        # 2. G'azab yoki shikoyat so'zlari (uz / ru / en)
        for pat in ANGER_COMPLAINT_PATTERNS:
            if re.search(pat, t, re.IGNORECASE):
                return True, REASON_ANGER_COMPLAINT

        return False, None

    @classmethod
    def is_unknown_answer(cls, reply: str) -> bool:
        """Bot javobi noma'lum ma'lumot yoki bilmaslikni ifodalashini tekshirish"""
        if not reply:
            return False
        r_low = reply.lower().strip()
        for pat in UNKNOWN_PATTERNS:
            if re.search(pat, r_low, re.IGNORECASE):
                return True
        return False

    @classmethod
    def get_consecutive_unknown_count(cls, chat_id: int) -> int:
        return cls._CONSECUTIVE_UNKNOWN_TRACKER.get(chat_id, 0)

    @classmethod
    def increment_consecutive_unknown(cls, chat_id: int) -> int:
        val = cls._CONSECUTIVE_UNKNOWN_TRACKER.get(chat_id, 0) + 1
        cls._CONSECUTIVE_UNKNOWN_TRACKER[chat_id] = val
        return val

    @classmethod
    def reset_consecutive_unknown(cls, chat_id: int) -> None:
        cls._CONSECUTIVE_UNKNOWN_TRACKER[chat_id] = 0

    # ---------------------------------------------------------
    # 3. 5-Qatorlik Muloqot Xulosasi (5-line Chat Summary)
    # ---------------------------------------------------------
    @classmethod
    def generate_5_line_summary(
        cls,
        chat_id: int,
        history: Optional[List[Dict[str, str]]] = None,
        reason: str = ""
    ) -> str:
        """
        Muloqot tarixidan QAT'IY 5 ta qatordan iborat xulosa tuzish.
        LLM (Gemini) yoki deterministik zaxira algoritmi orqali generatsiya qilinadi.
        """
        history = history or []

        # LLM chaqiruvi (Gemini orqali xulosa chiqarishga urinish)
        from config import GEMINI_API_KEY
        if GEMINI_API_KEY and len(history) >= 2:
            try:
                import google.generativeai as genai
                genai.configure(api_key=GEMINI_API_KEY)
                model = genai.GenerativeModel("gemini-3.8-flash")

                hist_text = "\n".join([f"{m.get('role')}: {m.get('content')}" for m in history[-10:]])
                prompt = (
                    "Quyidagi mijoz va do'kon boti muloqotini QAT'IY 5 TA QATORDA xulosa qilib ber.\n"
                    "QOIDALAR:\n"
                    "- Matn aynan 5 ta qatordan iborat bo'lsin.\n"
                    "- Har bir qator '1. ', '2. ', '3. ', '4. ', '5. ' bilan boshlansin.\n"
                    "- Faktlarga asoslangan qisqa va aniq bo'lsin.\n"
                    f"Sabab: {reason}\n\n"
                    f"Muloqot:\n{hist_text}\n\n"
                    "5-qatorli xulosa:"
                )
                resp = model.generate_content(prompt, generation_config={"temperature": 0.2})
                if resp and resp.text:
                    lines = [ln.strip() for ln in resp.text.split("\n") if ln.strip()]
                    if len(lines) == 5:
                        formatted = []
                        for idx, ln in enumerate(lines, 1):
                            clean_ln = re.sub(r"^\d+[\.\)]\s*", "", ln)
                            formatted.append(f"{idx}. {clean_ln}")
                        return "\n".join(formatted)
            except Exception as e:
                logger.warning(f"LLM 5-line summary generation fallback: {e}")

        # Deterministik zaxira generator (Always guaranteed 5 lines)
        user_msgs = [m.get("content", "").strip() for m in history if m.get("role") == "user" and m.get("content")]
        bot_msgs = [m.get("content", "").strip() for m in history if m.get("role") == "assistant" and m.get("content")]

        first_req = user_msgs[0] if user_msgs else "Mijoz do'konimiz bilan muloqotni boshladi"
        last_req = user_msgs[-1] if user_msgs else "Mijozning so'nggi xabari"
        last_ans = bot_msgs[-1] if bot_msgs else "Bot salomlashdi va menyuni taqdim etdi"

        # Mahsulot qiziqishi
        prod_mentions = [
            w for w in ["kurtka", "futbolka", "shim", "poyabzal", "krossovka", "xudi", "ko'ylak", "palto"]
            if any(w in m.lower() for m in user_msgs)
        ]
        topic = f"Mijoz {', '.join(prod_mentions)} bo'yicha qiziqdi" if prod_mentions else "Mijoz do'kon assortimenti va xizmatlari bilan qiziqdi"

        line1 = f"1. Boshlang'ich murojaat: {first_req[:80]}"
        line2 = f"2. Qiziqish mavzusi: {topic}"
        line3 = f"3. Bot taqdim etgan oxirgi ma'lumot: {last_ans[:80]}"
        line4 = f"4. Mijozning oxirgi xabari: {last_req[:80]}"
        line5 = f"5. Yo'naltirish sababi va holat: {reason}"

        return f"{line1}\n{line2}\n{line3}\n{line4}\n{line5}"

    # ---------------------------------------------------------
    # 4. Handoff Sessiyasini Boshlash (Start Handoff)
    # ---------------------------------------------------------
    @classmethod
    def start_handoff(
        cls,
        chat_id: int,
        customer_name: str,
        username: str = "",
        reason: str = REASON_HUMAN_REQUEST,
        history: Optional[List[Dict[str, str]]] = None
    ) -> Dict[str, Any]:
        """
        Handoff sessiyasini faollashtirish:
        - Sessiyani data/handoff_sessions.json ga yozish
        - 5-qatorlik xulosa tuzish
        - Admin uchun xabarni tayyorlash
        """
        now_iso = datetime.now().isoformat()
        summary_5_lines = cls.generate_5_line_summary(chat_id, history=history, reason=reason)

        clean_username = f"@{username}" if username and not username.startswith("@") else (username or "yo'q")

        admin_message = (
            f"🔔 **Mijoz jonli operatorga yo'naltirildi!**\n\n"
            f"👤 **Mijoz:** {customer_name} ({clean_username})\n"
            f"🆔 **Chat ID:** `{chat_id}`\n"
            f"⚠️ **Sabab:** {reason}\n\n"
            f"📝 **Muloqot xulosasi (5 qator):**\n"
            f"{summary_5_lines}\n\n"
            f"💬 *Javob berish uchun ushbu xabarga reply qiling yoki `/bot_on {chat_id}` yuboring.*"
        )

        session = {
            "chat_id": chat_id,
            "customer_name": customer_name,
            "username": clean_username,
            "reason": reason,
            "status": "active",
            "started_at": now_iso,
            "last_activity_at": now_iso,
            "summary": summary_5_lines
        }

        sessions = cls._load_sessions()
        sessions[str(chat_id)] = session
        cls._save_sessions(sessions)

        # Ketma-ket noma'lum sanog'ini tozalash
        cls.reset_consecutive_unknown(chat_id)

        # Agar admin alert sender o'rnatilgan bo'lsa, xabarnoma yuborish
        if cls._ADMIN_ALERT_SENDER:
            try:
                cls._ADMIN_ALERT_SENDER(admin_message, chat_id)
            except Exception as e:
                log_bot_error(chat_id, f"Admin alert trigger failed: {e}", exc=e)

        return {
            "customer_reply": CUSTOMER_HANDOFF_REPLY,
            "admin_message": admin_message,
            "summary": summary_5_lines,
            "session": session
        }

    # ---------------------------------------------------------
    # 5. Sessiya Holati va 6 Soatlik Sukut Tekshiruvi
    # ---------------------------------------------------------
    @classmethod
    def check_and_process_handoff(cls, chat_id: int) -> Tuple[bool, Optional[str]]:
        """
        Handoff holatini tekshirish:
        Qaytaradi: (is_in_handoff: bool, auto_return_message: Optional[str])
        - Agar 6 soat sukut bo'lsa -> Sessiyani yakunlab, auto_return_message qaytaradi.
        - Agar faol bo'lsa -> (True, None) (Bot jim turadi).
        - Agar nofaol bo'lsa -> (False, None).
        """
        sessions = cls._load_sessions()
        session = sessions.get(str(chat_id))
        if not session or session.get("status") != "active":
            return False, None

        # 6 soatlik sukutni tekshirish
        last_act_str = session.get("last_activity_at") or session.get("started_at")
        if last_act_str:
            try:
                last_act = datetime.fromisoformat(last_act_str)
                now = datetime.now()
                elapsed = (now - last_act).total_seconds()
                if elapsed >= cls.AUTO_RETURN_TIMEOUT_SECONDS:
                    # 6 soatdan oshgan -> Avto-qaytarish
                    session["status"] = "resolved"
                    session["resolution"] = "auto_return_6h"
                    session["resolved_at"] = now.isoformat()
                    sessions[str(chat_id)] = session
                    cls._save_sessions(sessions)
                    log_bot_error(chat_id, "Handoff session auto-returned to bot after 6 hours of silence.")
                    return False, AUTO_RETURN_MESSAGE
            except Exception as e:
                logger.error(f"Error checking elapsed time for handoff chat {chat_id}: {e}")

        # Handoff faol, bot jim turadi
        return True, None

    @classmethod
    def is_active_session(cls, chat_id: int) -> bool:
        """Chat hozirda faol handoff holatidami?"""
        in_handoff, _ = cls.check_and_process_handoff(chat_id)
        return in_handoff

    @classmethod
    def record_admin_activity(cls, chat_id: int) -> None:
        """Admin javob yozganda oxirgi faollik vaqtini yangilash (6 soatlik taymerni yangilaydi)"""
        sessions = cls._load_sessions()
        cid_str = str(chat_id)
        if cid_str in sessions and sessions[cid_str].get("status") == "active":
            sessions[cid_str]["last_activity_at"] = datetime.now().isoformat()
            cls._save_sessions(sessions)

    # ---------------------------------------------------------
    # 6. Botga qaytarish (/bot_on <chat_id>)
    # ---------------------------------------------------------
    @classmethod
    def resolve_handoff(cls, chat_id: int, resolved_by: str = "admin_command") -> bool:
        """
        Handoff sessiyasini yakunlash va chatni botga qaytarish.
        """
        sessions = cls._load_sessions()
        cid_str = str(chat_id)
        if cid_str not in sessions:
            return False

        sessions[cid_str]["status"] = "resolved"
        sessions[cid_str]["resolved_at"] = datetime.now().isoformat()
        sessions[cid_str]["resolution"] = resolved_by
        cls._save_sessions(sessions)
        cls.reset_consecutive_unknown(chat_id)
        return True
